file://C:/laragon/www/TS_CUSTOM_INTERPRETER/ep11-user-defined-functions/frontend/ast.ts
file://C:/laragon/www/TS_CUSTOM_INTERPRETER/ep11-user-defined-functions/frontend/lexer.ts
file://C:/laragon/www/TS_CUSTOM_INTERPRETER/ep11-user-defined-functions/frontend/parser.ts
file://C:/laragon/www/TS_CUSTOM_INTERPRETER/ep11-user-defined-functions/main.ts
file://C:/laragon/www/TS_CUSTOM_INTERPRETER/ep11-user-defined-functions/runtime/environment.ts
file://C:/laragon/www/TS_CUSTOM_INTERPRETER/ep11-user-defined-functions/runtime/eval/expressions.ts
file://C:/laragon/www/TS_CUSTOM_INTERPRETER/ep11-user-defined-functions/runtime/eval/statements.ts
file://C:/laragon/www/TS_CUSTOM_INTERPRETER/ep11-user-defined-functions/runtime/interpreter.ts
file://C:/laragon/www/TS_CUSTOM_INTERPRETER/ep11-user-defined-functions/runtime/values.ts
file://C:/laragon/www/TS_CUSTOM_INTERPRETER/ep11-user-defined-functions/test.txt
